#!/bin/sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output eDP-1 --mode 1920x1080 --rate 60.00 --output HDMI-1 --mode 1920x1080 --rate 120.00 --left-of eDP-1 --primary

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Do keyboard things here apparently?
setxkbmap -model pc104 -layout us\(dvorak\),us -option caps:swapescape,grp:alt_caps_toggle
exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
