#!/bin/sh
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output eDP-1 --mode 1920x1080 --rate 60.00 --output HDMI-1 --mode 1920x1080 --rate 120.00 --right-of eDP-1 --primary ||\
xrandr --output eDP-1 --mode 1920x1080 --rate 60.00 --primary
